# Generated by Django 2.0.4 on 2018-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='序列号SN'),
        ),
    ]
