# Generated by Django 2.0.4 on 2018-08-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('virtual', '虚拟机'), ('firewall', '防火墙'), ('route', '路由器'), ('switch', '交换机'), ('other', '其他')], max_length=32, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='manufactory',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asset.Manufactory', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='内存大小(GB)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('CentOS', 'CentOS'), ('Redhat', 'Redhat'), ('Ubuntu', 'Ubuntu')], max_length=32, null=True, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='supplier',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asset.Supplier', verbose_name='供应商'),
        ),
    ]
