# Generated by Django 2.0.4 on 2018-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('virtual', '虚拟机'), ('firewall', '防火墙'), ('route', '路由器'), ('switch', '交换机'), ('other', '其他')], max_length=32, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('centos', 'CentOS'), ('redhat', 'Redhat'), ('ubuntu', 'Ubuntu')], max_length=32, null=True, verbose_name='系统类型'),
        ),
    ]
