# Generated by Django 2.0.4 on 2018-05-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180420_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('服务器', '服务器'), ('virtual', '虚拟机'), ('firewall', '防火墙'), ('router', '路由器'), ('switch', '防火墙'), ('others', '其他')], max_length=32, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='资产编号'),
        ),
    ]
