# Generated by Django 2.0.4 on 2018-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180702_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('CentOS', 'CentOS'), ('Redhat', 'Redhat'), ('Ubuntu', 'Ubuntu')], max_length=32, null=True, verbose_name='系统类型'),
        ),
    ]
