# Generated by Django 2.0.4 on 2018-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180612_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('虚拟机', '虚拟机'), ('防火墙', '防火墙'), ('路由器', '路由器'), ('交换机', '交换机'), ('其他', '其他')], max_length=32, verbose_name='资产类型'),
        ),
    ]
