# Generated by Django 2.0.4 on 2018-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180809_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='机房名称'),
        ),
    ]
