# Generated by Django 2.0.4 on 2018-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180517_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('服务器', '服务器'), ('虚拟机', '虚拟机'), ('防火墙', '防火墙'), ('路由器', '路由器'), ('路由器', '防火墙'), ('其他', '其他')], max_length=32, verbose_name='资产类型'),
        ),
    ]
