# Generated by Django 2.0.4 on 2018-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180613_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('virtual', '虚拟机'), ('firewall', '防火墙'), ('route', '路由器'), ('switch', '交换机'), ('other', '其他')], max_length=32, verbose_name='资产类型'),
        ),
    ]
