# Generated by Django 2.0.4 on 2018-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180711_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mem_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存大小(GB)'),
        ),
    ]
