# Generated by Django 2.0.4 on 2018-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180517_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_managemant',
            field=models.GenericIPAddressField(unique=True, verbose_name='管理IP'),
        ),
    ]
