# Generated by Django 2.0.4 on 2018-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180711_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mem_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='内存大小(GB)'),
        ),
    ]
