# Generated by Django 2.0.4 on 2018-07-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20180713_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manufactory',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Manufactory', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='supplier',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Supplier', verbose_name='供应商'),
        ),
    ]
