# Generated by Django 2.0.4 on 2018-07-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20180725_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manufactory',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asset.Manufactory', verbose_name='制造商'),
        ),
    ]
