# Generated by Django 2.0.4 on 2018-07-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20180725_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='supplier',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asset.Supplier', verbose_name='供应商'),
        ),
    ]
